name: waitinglist workflow
on:
  push:
    branches: [ "feature-A" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: waitlist-aallie    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                


permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache Node modules
        uses: actions/cache@v4
        with: 
          path: ~/.npm 
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} 
          restore-keys: | 
               ${{ runner.os }}-node-

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version:  ${{ env.NODE_VERSION }}

      - name: Install dependencies, build react app
        run: |
          npm ci
          # npm run build
          npm install --save-dev @babel/plugin-proposal-private-property-in-object
      - name: Build React app
        run: | 
          CI=false npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
           name: production-artifact
           path: ./build

  deploy:
    permissions:
      contents: read
      packages: write 
        
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download production artifacts
        uses: actions/download-artifact@v4
        with: 
          name: production-artifact
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
         
      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}  